package com.example.jetpackcomposestarter.module.travel.tafmanagers

import com.example.jetpackcomposestarter.data.local.entities.TravelAuthorisationEntity
import java.util.*

data class TravelAuthorization(
    var id: Long,
    var employeeId: Long,
    var employeeNo: String,
    var name: String?,
    var localOversea: String,
    var destination: String,
    var dateStart: Date,
    var dateEnd: Date,
    var transport: String,
    var cashAdvance: Boolean?,
    var advanceAmount: Double?,
    var remarks: String,
    var personId: Long,
    var dateCreated: Date,
    var createdBy: Long,
    var dateModified: Date,
    var modifiedBy: Long,
    var dateSubmitted: Date?,
    var submittedByPersonId: Long?,
    var applicationSource: String?,
    var applicationStatus: String,
    var applicationReferenceNumber: String,
    var currentApprovers: String,
    var dateCurrentApprovalStart: Date?,
    var dateWorkflowCompleted: Date?,
    var approverComments: String?,
    var remarksBackOffice: String?,
    var inbound: String?,
    var outbound: String?,
    var booked: Boolean?,
    var bookedDate: Date?,
    var chargedToCompanyId: Long?,
    var chargedToCostCenterId: Long?,
    var returnToOffice: Date?,
    var applicationFolderId: Long?,
    var miscText1: String?,
    var miscText2: String?,
    var miscText3: String?,
    var miscBigText1: String?,
    var miscBigText2: String?,
    var miscBigText3: String?,
    var miscNum1: Double?,
    var miscNum2: Double?,
    var miscNum3: Double?,
    var miscDate1: Date?,
    var miscDate2: Date?,
    var miscDate3: Date?,
    var miscBool1: Boolean?,
    var miscBool2: Boolean?,
    var miscBool3: Boolean?,
//    val travellers: List<TafApplicationTraveller>? = null,
//    val tafApplicationTravellers: List<TafApplicationTraveller>? = null,
//    val tafApplicationItineraries: List<TafApplicationItinerary>? = null,
//    val attachments:List<Attachment>?=null,
//    var workflowComments:List<WorkflowComment>?=null,
)

fun TravelAuthorization.toEntity() = TravelAuthorisationEntity(
    id = this.id,
    employeeId = this.employeeId,
    employeeNo = this.employeeNo,
    personId = this.personId,
    localOversea = this.localOversea,
    destination = this.destination,
    dateStart = this.dateStart,
    dateEnd = this.dateEnd,
    inbound = this.inbound,
    outbound = this.outbound,
    transport = this.transport,
    remarks = this.remarks,
    dateCreated = this.dateCreated,
    createdBy = this.createdBy,
    dateModified = this.dateModified,
    modifiedBy = this.modifiedBy,
    dateSubmitted = this.dateSubmitted,
    submittedByPersonId = this.submittedByPersonId,
    actionedByPersonId = null, // If not tracked in original model
    applicationSource = this.applicationSource ?: "",
    applicationStatus = this.applicationStatus,
    applicationReferenceNumber = this.applicationReferenceNumber,
    currentApprovers = this.currentApprovers,
    dateCurrentApprovalStart = this.dateCurrentApprovalStart,
    dateWorkflowCompleted = this.dateWorkflowCompleted,
    workflowComment = this.approverComments ?: ""
)


