package com.example.jetpackcomposestarter.shared.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0080C5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA8DFF1)
val md_theme_light_onPrimaryContainer = Color(0xFF001F30)
val md_theme_light_secondary = Color(0xFF73B0CD)
val md_theme_light_onSecondary = Color(0xFF001E2B)
val md_theme_light_secondaryContainer = Color(0xFFD1EEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1B3A46)
val md_theme_light_tertiary = Color(0xFFA8DFF1)
val md_theme_light_onTertiary = Color(0xFF002D3A)
val md_theme_light_tertiaryContainer = Color(0xFFF9F9FA)
val md_theme_light_onTertiaryContainer = Color(0xFF0B1E24)
val md_theme_light_error = Color(0xFFB70404)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7F7F4)
val md_theme_light_onBackground = Color(0xFF1C1C1C)
val md_theme_light_surface = Color(0xFFF7F7F4)
val md_theme_light_onSurface = Color(0xFF1C1C1C)
val md_theme_light_surfaceContainer = Color(0xFFF7F7FB)
val md_theme_light_surfaceVariant = Color(0xFFE0E8EA)
val md_theme_light_onSurfaceVariant = Color(0xFF3A4446)
val md_theme_light_outline = Color(0xFFBABEC1) //Textfield outline
val md_theme_light_outlineVariant = Color(0xFFE6E6E6) //Decorative element eg: divider/chips
//Toast Message
val md_theme_light_inverseSurface = Color(0xFF2C3134) //Bg fills
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F1) //Text or icons
val md_theme_light_inversePrimary = Color(0xFF73B0CD) //Actionable elements eg: text buttons
val md_theme_light_surfaceTint = Color(0xFF0080C5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_scrim = Color(0xFF000000)


val md_theme_dark_primary = Color(0xFF5BA7C2)
val md_theme_dark_onPrimary = Color(0xFF0A2F3A)
val md_theme_dark_primaryContainer = Color(0xFF2F4D59)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1EEF8)
val md_theme_dark_secondary = Color(0xFF89B4C5)
val md_theme_dark_onSecondary = Color(0xFFDCDCDC)
val md_theme_dark_secondaryContainer = Color(0xFF374D58)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1EEF8)
val md_theme_dark_tertiary = Color(0xFF9ACED7)
val md_theme_dark_onTertiary = Color(0xFF1D3F45)
val md_theme_dark_tertiaryContainer = Color(0xFF353535)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0F7FB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF690003)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF252525)
val md_theme_dark_onBackground = Color(0xFFEBEBF5)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE3E3E3)
val md_theme_dark_surfaceContainer = Color(0xFF252525)
val md_theme_dark_surfaceVariant = Color(0xFF40494B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8CA)
val md_theme_dark_outline = Color(0xFF383838)
val md_theme_dark_outlineVariant = Color(0xFF4F585A)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C1C)
val md_theme_dark_inverseSurface = Color(0xFFE3E3E3)
val md_theme_dark_inversePrimary = Color(0xFF73B0CD)
val md_theme_dark_surfaceTint = Color(0xFF66C9FF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_scrim = Color(0xFF000000)


val ModulePendingItems = Color(0xFFF0628B)
val ModuleCheckIn = Color(0xFF0073E6)
val ModuleLeave = Color(0xFFF7B040)
val ModuleClaims = Color(0xFF0CA696)
val ModuleTimeInLieu = Color(0xFF33CC33)
val ModulePayslip = Color(0xFF985FA7)
val ModuleSchedule = Color(0xFF4E98B0)
val ModuleTravel = Color(0xFFFF6F61)
